export const perfumes = [
    {
        "pid": "n4qcwQ",
        "brand": "Dupetit",
        "name": "Eau de Jasmin",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/f4/f4740a-eau-de-jasmin-dupetit_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": "DE",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.45,
        "ratingVotes": 15,
        "longevity": 3.4,
        "sillage": 3.16,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Floral\",\"Earthy\",\"Spicy\",\"Animal\",\"Chypre\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Jasmine Sambac\",\"Lemon Petitgrain\",\"Orange Blossom Absolute\"]"
    },
    {
        "pid": "UOHgkd",
        "brand": "Deco",
        "name": "Quentin",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/57/57448b-quentin-deco_1200.jpg",
        "imgs": "[]",
        "sex": "M",
        "origin": "GB",
        "year": 2015,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.89,
        "ratingVotes": 11,
        "longevity": 4,
        "sillage": 3.6,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Robertet\"]",
        "designers": null,
        "accords": "[\"Floral\",\"Earthy\",\"Woody\",\"Spicy\",\"Green\"]",
        "top": "[\"Bergamot\",\"Cinnamon\",\"Tarragon\"]",
        "heart": "[\"Carnation\",\"Geranium\",\"Patchouli\"]",
        "base": "[\"Leather\",\"Moss\",\"Musk\",\"Sandalwood\",\"Vetiver\"]"
    },
    {
        "pid": "KyrsKD",
        "brand": "Dali Haute Parfumerie",
        "name": "Fluidité du Temps Imaginaire",
        "parent": "Cofinluxe / Cofci",
        "img": "https://media.parfumo.com/perfumes/5a/5ac27b-fluidite-du-temps-imaginaire-dali-haute-parfumerie_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/77/77d9b8-fluidite-du-temps-imaginaire-dali-haute-parfumerie_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/bf/bfa6ba-fluidite-du-temps-imaginaire-dali-haute-parfumerie_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/33/335b0f-fluidite-du-temps-imaginaire-dali-haute-parfumerie_1200.jpg\"]",
        "sex": "U",
        "origin": "FR",
        "year": 2016,
        "type": "M",
        "available": "M",
        "limited": "N",
        "collector": "N",
        "rating": 4,
        "ratingVotes": 127,
        "longevity": 3.92,
        "sillage": 3.72,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Alberto Morillas\"]",
        "designers": null,
        "accords": "[\"Floral\",\"Sweet\",\"Spicy\",\"Citrus\",\"Fresh\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Indian Tuberose\",\"Bergamot\",\"Saffron\",\"Bourbon Vanilla\",\"Sandalwood\",\"Ambrox\",\"Jasmine Sambac\"]"
    },
    {
        "pid": "bttCHc",
        "brand": "Blackcliff",
        "name": "Hidden Hills",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/d7/d77747-hidden-hills-blackcliff_1200.jpg",
        "imgs": "[]",
        "sex": "U",
        "origin": "BB",
        "year": 2023,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.76,
        "ratingVotes": 10,
        "longevity": 3.4,
        "sillage": 3.6,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Kyle Mott-Kannenberg Perfume maker, Brand owner [OSM]\"]",
        "designers": null,
        "accords": "[\"Green\",\"Powdery\",\"Leathery\",\"Woody\",\"Floral\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Bergamot\",\"Black Tea\",\"Cypress\",\"Italian Lemon\",\"Lavender\",\"Pink Pepper\",\"Smoke\",\"Texas Cedar\",\"Tobacco\",\"Vanilla\"]"
    },
    {
        "pid": "MvjT0p",
        "brand": "Apart",
        "name": "Agua Tropical",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/97/97205b-agua-tropical-apart_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": null,
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.63,
        "ratingVotes": 28,
        "longevity": 3.8,
        "sillage": 3.44,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Kim Weisswange\"]",
        "designers": null,
        "accords": "[\"Floral\",\"Fruity\",\"Green\",\"Aquatic\",\"Fresh\"]",
        "top": "[\"Mango\",\"Papaya\",\"Passion Fruit\",\"Pink Grapefruit\",\"Tangerine\"]",
        "heart": "[\"Blackcurrant\",\"Jasmine\",\"Rose\",\"Ylang-ylang\"]",
        "base": "[\"Sandalwood\",\"Vanilla\"]"
    },
    {
        "pid": "JUehjv",
        "brand": "Diana Vreeland",
        "name": "Outrageous - Outrageously Vibrant",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/63/63f91f-outrageous-outrageously-vibrant-diana-vreeland_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": "US",
        "year": 2016,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.93,
        "ratingVotes": 39,
        "longevity": 3.84,
        "sillage": 3.6,
        "video": null,
        "brandUrl": "https://www.dianavreelandparfums.com",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.2020.jpg",
        "perfumers": "[\"Carlos Benaïm\",\"IFF (International Flavors & Fragrances)\"]",
        "designers": null,
        "accords": "[\"Spicy\",\"Oriental\",\"Woody\",\"Earthy\",\"Floral\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Patchouli\",\"Rose\",\"Blackcurrant\",\"Oud\"]"
    },
    {
        "pid": "QjZ9ba",
        "brand": "Scents of Time",
        "name": "Maya - Mystic Scent of the Americas",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/4b/4b1f8c-maya-mystic-scent-of-the-americas-scents-of-time_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": null,
        "year": 2009,
        "type": "M",
        "available": "N",
        "limited": "N",
        "collector": "N",
        "rating": 3.77,
        "ratingVotes": 33,
        "longevity": 3.52,
        "sillage": 3.68,
        "video": null,
        "brandUrl": "https://www.scentsoftime.co.uk",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.460.jpg",
        "perfumers": "[\"Jorge Lee\"]",
        "designers": null,
        "accords": "[\"Gourmand\",\"Resinous\",\"Floral\",\"Sweet\",\"Oriental\"]",
        "top": "[\"Copaiba Balsam\"]",
        "heart": "[\"Floral Notes\",\"Green Notes\",\"Jasmine\",\"Exotic Fruits\"]",
        "base": "[\"Cocoa\",\"Vanilla\"]"
    },
    {
        "pid": "6qlGrR",
        "brand": "Fragrances of Ireland",
        "name": "Connemara",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/66/6672bc-connemara-fragrances-of-ireland_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": "IE",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.97,
        "ratingVotes": 217,
        "longevity": 4.08,
        "sillage": 3.8,
        "video": null,
        "brandUrl": "https://www.perfume.ie/",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.636.jpg",
        "perfumers": "[\"Arthur Burnham\"]",
        "designers": null,
        "accords": "[\"Floral\",\"Green\",\"Fresh\",\"Powdery\",\"Spicy\"]",
        "top": "[\"Lily Of The Valley\",\"Freesia\",\"Violet\"]",
        "heart": "[\"Carnation\",\"Rose\",\"Mimosa\"]",
        "base": "[\"Musk\",\"Sandalwood\",\"Vanilla\",\"Iris\",\"Peach\"]"
    },
    {
        "pid": "3cxaCp",
        "brand": "Hunkemöller",
        "name": "Forever Sexy",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/22/229bae-forever-sexy-hunkemoller_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": "NL",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 2.91,
        "ratingVotes": 9,
        "longevity": 3.12,
        "sillage": 2.6,
        "video": null,
        "brandUrl": "https://www.hunkemoller.com",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.1379.jpg",
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Fruity\",\"Floral\",\"Sweet\"]",
        "top": "[\"Bergamot\",\"Grapefruit\",\"Lime\",\"Orange\"]",
        "heart": "[\"Jasmine\",\"Peach\",\"Rose\",\"Violet\"]",
        "base": "[\"Sandalwood\",\"Vanilla\"]"
    },
    {
        "pid": "9QVngX",
        "brand": "Provence Santé",
        "name": "Tilleul",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/6c/6cd593-tilleul-linden-provence-sante_1200.jpg",
        "imgs": "[]",
        "sex": "U",
        "origin": "FR",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.37,
        "ratingVotes": 28,
        "longevity": 3.6,
        "sillage": 3.08,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Floral\",\"Fresh\",\"Sweet\",\"Green\",\"Spicy\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[]"
    },
    {
        "pid": "CvBPye",
        "brand": "Asabi",
        "name": "№ 5 Intense",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/80/80e583-5-intense-asabi_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/26/261dfc-5-intense-asabi_1200.jpg\"]",
        "sex": "U",
        "origin": "DE",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 4,
        "ratingVotes": 268,
        "longevity": 4.16,
        "sillage": 4.04,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Powdery\",\"Spicy\",\"Floral\",\"Sweet\",\"Fresh\"]",
        "top": "[\"Lavender\"]",
        "heart": "[\"Myrrh\"]",
        "base": "[\"Tonka Bean\",\"Vanilla\",\"Almond\"]"
    },
    {
        "pid": "gg5NOf",
        "brand": "Diane von Furstenberg",
        "name": "Volcan d'Amour",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/8b/8b9f2e-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/9c/9ccb7b-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/5d/5d6fcb-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/a1/a1e052-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/0a/0ad830-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/a2/a24a70-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/7d/7ded66-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/b7/b706b2-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/a9/a9e8ae-volcan-d-amour-eau-de-toilette-diane-von-furstenberg_1200.jpg\"]",
        "sex": "F",
        "origin": "US",
        "year": 1981,
        "type": "EDT",
        "available": "N",
        "limited": "N",
        "collector": "N",
        "rating": 4.24,
        "ratingVotes": 11,
        "longevity": null,
        "sillage": 4.52,
        "video": null,
        "brandUrl": "https://www.dvf.com",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.1005.jpg",
        "perfumers": "[]",
        "designers": "Dakota Jackson, Antonio Piticov",
        "accords": "[\"Chypre\",\"Floral\",\"Woody\",\"Powdery\",\"Sweet\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Floral Notes\",\"Frankincense\",\"Myrrh\",\"Oakmoss\",\"Woody Notes\"]"
    },
    {
        "pid": "xEhxoy",
        "brand": "Our Projects",
        "name": "Suede Honey",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/05/059093-suede-honey-our-projects_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/01/01c73d-suede-honey-our-projects_1200.jpg\"]",
        "sex": "U",
        "origin": "ID",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.92,
        "ratingVotes": 3,
        "longevity": null,
        "sillage": null,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Floral\",\"Synthetic\",\"Sweet\",\"Creamy\"]",
        "top": "[\"Magnolia\",\"Wild Honey\"]",
        "heart": "[\"Sandalwood\",\"White Musk\"]",
        "base": "[\"Amber\",\"Tonka Bean\",\"Vanilla\"]"
    },
    {
        "pid": "1XU9H0",
        "brand": "Brut (Unilever)",
        "name": "Brut",
        "parent": "Unilever",
        "img": "https://media.parfumo.com/perfumes/73/73b313-brut-after-shave-brut-unilever_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/df/df6a3b-brut-after-shave-brut-unilever_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/3f/3fa958-brut-after-shave-brut-unilever_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/c6/c66ad0-brut-after-shave-brut-unilever_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/4d/4d272b-brut-after-shave-brut-unilever_1200.jpg\"]",
        "sex": "M",
        "origin": "GB",
        "year": 1964,
        "type": "M",
        "available": "M",
        "limited": "N",
        "collector": "N",
        "rating": 3.64,
        "ratingVotes": 83,
        "longevity": 3.24,
        "sillage": 3.4,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Karl Mann\"]",
        "designers": null,
        "accords": "[\"Spicy\",\"Floral\",\"Fresh\",\"Woody\",\"Green\"]",
        "top": "[\"Neroli\",\"True Lavender\",\"Basil\"]",
        "heart": "[\"Geranium\",\"Fern\"]",
        "base": "[\"Sandalwood\",\"Patchouli\",\"White Musk\"]"
    },
    {
        "pid": "TRmk3k",
        "brand": "Yaemina",
        "name": "Endorphins 22 - What If",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/40/4036da-endorphins-22-what-if-yaemina_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/ff/ffeff8-endorphins-22-what-if-yaemina_1200.jpg\"]",
        "sex": "F",
        "origin": "CS",
        "year": null,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.4,
        "ratingVotes": 2,
        "longevity": null,
        "sillage": null,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Sweet\",\"Synthetic\",\"Gourmand\",\"Spicy\",\"Floral\"]",
        "top": "[\"Saffron\",\"Tagetes\"]",
        "heart": "[\"Amber\",\"Jasmine\"]",
        "base": "[\"Caramel\",\"Cashmere Wood\",\"Moss\",\"Vanilla\"]"
    },
    {
        "pid": "pf76VT",
        "brand": "Hors Là Monde",
        "name": "Lady Shiloh",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/1a/1a2aa5-lady-shiloh-hors-la-monde_1200.jpg",
        "imgs": "[]",
        "sex": "F",
        "origin": null,
        "year": 2009,
        "type": "M",
        "available": "N",
        "limited": "N",
        "collector": "N",
        "rating": 3.37,
        "ratingVotes": 34,
        "longevity": 3.4,
        "sillage": 3.2,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Fabrice Olivieri\"]",
        "designers": null,
        "accords": "[\"Floral\",\"Spicy\",\"Powdery\",\"Woody\",\"Fresh\"]",
        "top": "[\"Mandarin Orange\",\"Bergamot\"]",
        "heart": "[\"Jasmine\",\"Violet\"]",
        "base": "[\"Vetiver\",\"Patchouli\",\"White Musk\"]"
    },
    {
        "pid": "S78xss",
        "brand": "Ahjaar",
        "name": "Nepal",
        "parent": "Limar",
        "img": "https://media.parfumo.com/perfumes/60/602d40-nepal-ahjaar_1200.jpg",
        "imgs": "[]",
        "sex": "U",
        "origin": "AE",
        "year": 2014,
        "type": "M",
        "available": "M",
        "limited": "N",
        "collector": "N",
        "rating": 4.15,
        "ratingVotes": 28,
        "longevity": 4.12,
        "sillage": 3.8,
        "video": null,
        "brandUrl": "https://www.parisgallery.com/",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.1999.jpg",
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Oriental\",\"Woody\",\"Earthy\",\"Floral\",\"Animal\"]",
        "top": "[\"Rose\"]",
        "heart": "[\"Patchouli\"]",
        "base": "[\"Oud\"]"
    },
    {
        "pid": "idpbaa",
        "brand": "Teresa Helbig",
        "name": "Georgette",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/9d/9d1f0c-georgette-teresa-helbig_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/0a/0abd57-georgette-teresa-helbig_1200.jpg\"]",
        "sex": "F",
        "origin": "ES",
        "year": 2018,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.72,
        "ratingVotes": 20,
        "longevity": 3.96,
        "sillage": 3.4,
        "video": null,
        "brandUrl": "https://www.teresahelbig.com",
        "brandImg": "https://fimgs.net/mdimg/dizajneri/m.2972.jpg",
        "perfumers": "[]",
        "designers": null,
        "accords": "[\"Floral\",\"Spicy\",\"Woody\",\"Resinous\",\"Sweet\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Vanilla\",\"Benzoin\",\"Cardamom\",\"Cedarwood\",\"Magnolia\",\"Nutmeg\",\"Orange\",\"Sandalwood\",\"Grapefruit\",\"Mandarin Orange\",\"Labdanum\",\"Patchouli\"]"
    },
    {
        "pid": "b3OLkD",
        "brand": "Unifrom",
        "name": "Limbo",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/01/019e84-limbo-unifrom_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/aa/aa99a5-limbo-unifrom_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/65/658de3-limbo-unifrom_1200.jpg\"]",
        "sex": "U",
        "origin": "SE",
        "year": 2020,
        "type": "M",
        "available": "N",
        "limited": "N",
        "collector": "N",
        "rating": 3.92,
        "ratingVotes": 4,
        "longevity": null,
        "sillage": null,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Marie Schnirer\"]",
        "designers": null,
        "accords": "[\"Synthetic\",\"Woody\",\"Floral\",\"Sweet\"]",
        "top": "[]",
        "heart": "[]",
        "base": "[\"Hay\",\"Myrrh\",\"Rhubarb\",\"Sandalwood\",\"Vanilla\",\"White Musk\",\"Ylang-ylang\"]"
    },
    {
        "pid": "iBAaCZ",
        "brand": "Eau d'Italie",
        "name": "Fior Fiore",
        "parent": null,
        "img": "https://media.parfumo.com/perfumes/1a/1a3850-fior-fiore-eau-d-italie_1200.jpg",
        "imgs": "[\"https://media.parfumo.com/perfume_imagery/f5/f59964-fior-fiore-eau-d-italie_1200.jpg\",\"https://media.parfumo.com/perfume_imagery/70/7055f3-fior-fiore-eau-d-italie_1200.jpg\"]",
        "sex": "U",
        "origin": "IT",
        "year": 2018,
        "type": "M",
        "available": "Y",
        "limited": "N",
        "collector": "N",
        "rating": 3.61,
        "ratingVotes": 44,
        "longevity": 3.68,
        "sillage": 3.52,
        "video": null,
        "brandUrl": null,
        "brandImg": null,
        "perfumers": "[\"Olivier Cresp\"]",
        "designers": null,
        "accords": "[\"Fresh\",\"Floral\",\"Fruity\",\"Sweet\",\"Green\"]",
        "top": "[\"Lily Of The Valley\",\"Pear\"]",
        "heart": "[\"Jasmine\",\"Jasmine Sambac\"]",
        "base": "[\"Ambrette Seed\"]"
    }
]